version: '3.8'

services:
  # 1. The Database
  db:
    image: postgres:15-alpine
    container_name: cms_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cms_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # 2. The API (We will uncomment these later when we write the code)
  # api:
  #   build:
  #     context: .
  #     dockerfile: apps/api/Dockerfile
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@db:5432/cms_db

  # 3. The Worker (Uncomment later)
  # worker:
  #   build:
  #     context: .
  #     dockerfile: apps/worker/Dockerfile
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@db:5432/cms_db

volumes:
  db_data: